#!/usr/bin/env python

from pprint import pprint

import chartt
import ministryt
import arguments
import journalt
import initialt
import budgett

import report_ministry
import report_bills
import report_funds

################################################################


def accumulate_children(number, balance, chart):
    children = chart.account(number).children()
    if not children:
        return balance

    total = 0
    kind = chart.account(number).is_debit_account()
    for num in children:
        balance = accumulate_children(num, balance, chart)
        num_kind = chart.account(num).is_debit_account()
        total += balance.get(num, 0) * (1 if kind == num_kind else -1)
    balance[number] += total
    return balance

def balances(initial, journal, chart, start=None, end=None):

    # pylint: disable=too-many-locals

    prior_credit = {}
    prior_debit = {}
    period_credit = {}
    period_debit = {}
    for entry in journal.entries():
        num = entry.number()
        debit = entry.debit() or 0
        credit = entry.credit() or 0
        if entry.date_is(None, start):
            prior_debit[num] = prior_debit.get(num, 0) + debit
            prior_credit[num] = prior_credit.get(num, 0) + credit
            continue
        if entry.date_is(start, end):
            period_debit[num] = period_debit.get(num, 0) + debit
            period_credit[num] = period_credit.get(num, 0) + credit
            continue

    prior_balance = {}
    current_balance = {}
    activity = {}
    for num in chart.accounts():
        prior_balance[num] = initial.balance(num)
        current_balance[num] = initial.balance(num)

        prior_change = prior_debit.get(num, 0) - prior_credit.get(num, 0)
        period_change = period_debit.get(num, 0) - period_credit.get(num, 0)
        if chart.account(num).is_credit_account():
            prior_change = -prior_change
            period_change = -period_change

        prior_balance[num] += prior_change
        current_balance[num] += prior_change + period_change
        activity[num] = period_change

    for num in prior_balance:
        if chart.account(num).parent() is None:
            prior_balance = accumulate_children(num, prior_balance, chart)
            current_balance = accumulate_children(num, current_balance, chart)
            activity = accumulate_children(num, activity, chart)

    return {'prior': prior_balance, 'current': current_balance, 'activity': activity}

def main():
    arg = arguments.parse()
    chart = chartt.Chart(chart=arg.chart)
    initial = initialt.Initial(arg.initial)
    budget = budgett.Budget(arg.budget)
    ministry = ministryt.Ministry(coa=chart)
    journal = journalt.Journal(arg.journal)

    balance = balances(initial, journal, chart, arg.date_start, arg.date_end)

    if arg.dump_arguments:
        pprint(arg)
        return

    first_report = True

    if arg.bills:
        if not first_report:
            print "\f"
        first_report = False
        report_bills.bills_report(journal, chart,
                                  arg.date_start, arg.date_end,
                                  arg.posted_start, arg.posted_end,
                                  width=arg.line_width)

    if arg.subfunds:
        if not first_report:
            print "\f"
        first_report = False
        report_funds.subfund_report(arg.month_name, chart, balance,
                                    width=arg.line_width)

    if arg.ministries:
        if not first_report:
            print "\f"
        first_report = False
        report_ministry.ministry_reports(journal, balance, chart, budget,
                                         ministry, arg.month_name,
                                         arg.date_start, arg.date_end,
                                         arg.posted_start, arg.posted_end,
                                         width=arg.line_width)

    if arg.vendor_report:
        if not first_report:
            print "\f"
        first_report = False
        print "Vendor report not implemented"

    if arg.unassigned_report:
        if not first_report:
            print "\f"
        first_report = False
        print "Unassigned report no implemented"

if __name__ == "__main__":
    main()
