#!/usr/bin/env python

from pprint import pprint

import chartt
import ministryt
import arguments
import journalt
import initialt
import budgett

import report_ministry
import report_bills
import report_subfunds
import report_vendors
import report_accounts

import balancet

################################################################


def main():

    # pylint: disable=too-many-branches

    arg = arguments.parse()
    chart = chartt.Chart(chart=arg.chart)
    journal = journalt.Journal(arg.journal)
    initial = initialt.Initial(arg.initial)
    budget = budgett.Budget(arg.budget)
    ministry = ministryt.Ministry(coa=chart)

    balance = balancet.balances(chart, journal, initial, arg.date_start, arg.date_end)

    if arg.dump_arguments:
        pprint(arg)
        return

    first_report = True

    if arg.bills:
        if not first_report:
            print "\f"
        first_report = False
        report_bills.bills_report(chart, journal,
                                  arg.date_start, arg.date_end,
                                  arg.posted_start, arg.posted_end,
                                  width=arg.width)

    if arg.subfunds:
        if not first_report:
            print "\f"
        first_report = False
        report_subfunds.subfund_report(arg.month_name, chart, balance,
                                       width=arg.width)

    if arg.ministries:
        if not first_report:
            print "\f"
        first_report = False
        report_ministry.ministry_reports(chart, journal, budget, balance,
                                         ministry, arg.month_name,
                                         arg.date_start, arg.date_end,
                                         arg.posted_start, arg.posted_end,
                                         width=arg.width)

    if arg.vendors:
        if not first_report:
            print "\f"
        first_report = False
        report_vendors.vendor_report(chart, journal, balance,
                                     arg.date_start, arg.date_end,
                                     all_vendors=arg.all_vendors,
                                     width=arg.width)

    if arg.unassigned:
        if not first_report:
            print "\f"
        first_report = False
        print "Unassigned report no implemented"


    if arg.accounts:
        if not first_report:
            print "\f"
        first_report = False
        report_accounts.accounts_report(arg.month_name, arg.accounts,
                                        chart, journal, budget, balance,
                                        arg.date_start, arg.date_end,
                                        width=arg.width)

if __name__ == "__main__":
    main()
